#!/bin/bash
set -e
set -u

log() {
  echo -e "[update-version]  ${*}"
}

die() {
  log "${*}" && exit 1
}

# regular expressions
UV_REGEX_VERSION_TAG="^INS_VERSION=[0-9]{1,20}$";
UV_REGEX_VERSION="[0-9]{1,20}$";

# receive script
UV_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
UV_SCRIPT_NAME="install-server.sh"
UV_SCRIPT="${UV_SCRIPT_DIR}/${UV_SCRIPT_NAME}"

# validate script
[[ -f "${UV_SCRIPT}" ]] || (die "ERROR: missing script at ${UV_SCRIPT}.")

# receive current version
UV_CURRENT_TAG=$(grep -E "${UV_REGEX_VERSION_TAG}" "${UV_SCRIPT}")
log "current tag: ${UV_CURRENT_TAG}"
[[ "${UV_CURRENT_TAG}" == "" ]] && die "ERROR: can't receive version tag."
echo "${UV_CURRENT_TAG}" | wc

UV_CURRENT_VERSION=$(echo "${UV_CURRENT_TAG}" | grep -o -E "${UV_REGEX_VERSION}")
log "current version: ${UV_CURRENT_VERSION}"
[[ "${UV_CURRENT_VERSION}" == "" ]] && die "ERROR: can't receive version."

# calculate next version
UV_NEW_VERSION=$((UV_CURRENT_VERSION+1))
UV_NEW_TAG="INS_VERSION=${UV_NEW_VERSION}"


log "new version: ${UV_NEW_VERSION}"
log "new tag: ${UV_NEW_TAG}"

sed -n "s/${UV_CURRENT_TAG}/${UV_NEW_TAG}/gp" "${UV_SCRIPT}"

# print empty line on end
echo ""
